package lab6;

public enum Plants {
	NEEM, RED_BUCKEYE, DAPHNE, OREGON_GRAPE, HOLLY, CRABAPPLE, BOXWOOD, MAHONIA, AZALEA,
	MAPLE, ROSE, APPLE, HYDRANGEA, LAVENDER, PEAR, FRINGE, AUCUBA, FIG, FATSIA, OAK;
}
